CREATE TABLE IF NOT EXISTS BINARIES (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  EXTENSION CHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS BINARY_CONTENTS (
  HASH BINARY(32) NOT NULL,
  BINARY_ID UUID NOT NULL,
  UPLOADED TIMESTAMP NOT NULL,
  CONTENT BINARY NOT NULL,
  PRIMARY KEY (HASH, BINARY_ID),
  FOREIGN KEY (BINARY_ID) REFERENCES BINARIES(ID)
);